window.MAPBOX_CONFIG = {
  accessToken: "pk.REPLACE_WITH_YOUR_MAPBOX_ACCESS_TOKEN",
  style: "mapbox://styles/mapbox/standard",
  lightPreset: "day",
  showPointOfInterestLabels: false,
  showPlaceLabels: true,
  showRoadLabels: true,
  showTransitLabels: false,
  center: [-97.7431, 30.2672], // Austin, TX
  zoom: 12,
  pitch: 58,
  bearing: -25,
  useRoadRouting: true,
  routeProfile: "walking", // walking | cycling | driving
  // Set true to fetch additional places from Mapbox Search.
  loadPlacesFromMapbox: false,
  searchBbox: "-97.95,30.10,-97.56,30.52", // optional; [minLon,minLat,maxLon,maxLat]
  placesCatalog: [
    {
      id: "zilker-calisthenics",
      name: "Zilker Park Pull-up Bars",
      coordinates: [-97.7722, 30.2665],
      category: "calisthenics",
      address: "Barton Springs Rd, Austin, TX",
      website: "",
    },
    {
      id: "pease-fitness-court",
      name: "Pease Park Fitness Court",
      coordinates: [-97.7514, 30.2794],
      category: "calisthenics",
      address: "1100 Kingsbury St, Austin, TX",
      website: "https://peasepark.org",
    },
    {
      id: "republic-square-bars",
      name: "Republic Square Training Bars",
      coordinates: [-97.7464, 30.2672],
      category: "calisthenics",
      address: "422 Guadalupe St, Austin, TX",
      website: "",
    },
    {
      id: "butler-track",
      name: "Butler Track at Lady Bird Lake",
      coordinates: [-97.7389, 30.2631],
      category: "track",
      address: "920 W Riverside Dr, Austin, TX",
      website: "https://thetrailfoundation.org",
    },
    {
      id: "austin-high-track",
      name: "Austin High Public Track",
      coordinates: [-97.7608, 30.2809],
      category: "track",
      address: "1715 W Cesar Chavez St, Austin, TX",
      website: "",
    },
    {
      id: "eastside-track",
      name: "Eastside Memorial Track",
      coordinates: [-97.7026, 30.2729],
      category: "track",
      address: "1012 Arthur Stiles Rd, Austin, TX",
      website: "",
    },
    {
      id: "lady-bird-trail-auditorium",
      name: "Lady Bird Trail - Auditorium Shores",
      coordinates: [-97.7513, 30.2598],
      category: "trail",
      address: "900 W Riverside Dr, Austin, TX",
      website: "https://thetrailfoundation.org",
    },
    {
      id: "shoal-creek-trail",
      name: "Shoal Creek Trail",
      coordinates: [-97.7448, 30.2894],
      category: "trail",
      address: "Shoal Creek Blvd & W 12th St, Austin, TX",
      website: "",
    },
    {
      id: "barton-creek-greenbelt",
      name: "Barton Creek Greenbelt Trailhead",
      coordinates: [-97.8033, 30.2599],
      category: "trail",
      address: "3755 S Capital of Texas Hwy, Austin, TX",
      website: "",
    },
    {
      id: "walnut-creek-trail",
      name: "Walnut Creek Metropolitan Trail",
      coordinates: [-97.6732, 30.3676],
      category: "trail",
      address: "12138 N Lamar Blvd, Austin, TX",
      website: "",
    },
    {
      id: "mt-bonnell-climb",
      name: "Mount Bonnell Hill Repeats",
      coordinates: [-97.7732, 30.3212],
      category: "hill",
      address: "3800 Mount Bonnell Rd, Austin, TX",
      website: "",
    },
    {
      id: "south-lamar-hill",
      name: "South Lamar Incline",
      coordinates: [-97.7604, 30.2444],
      category: "hill",
      address: "South Lamar Blvd & Bluebonnet Ln, Austin, TX",
      website: "",
    },
    {
      id: "river-place-climb",
      name: "River Place Trail Climb",
      coordinates: [-97.8792, 30.3716],
      category: "hill",
      address: "8820 Big View Dr, Austin, TX",
      website: "",
    },
    {
      id: "barton-hills-stairs",
      name: "Barton Hills Stair Set",
      coordinates: [-97.7872, 30.2538],
      category: "stairs",
      address: "Barton Hills Dr, Austin, TX",
      website: "",
    },
    {
      id: "ut-stadium-steps",
      name: "UT Stadium Steps",
      coordinates: [-97.7325, 30.2839],
      category: "stairs",
      address: "405 E 23rd St, Austin, TX",
      website: "https://texassports.com",
    },
  ],
  defaultRun: ["zilker-calisthenics", "butler-track", "lady-bird-trail-auditorium"],
  communityRuns: [
    {
      id: "downtown-fitness-circuit",
      name: "Downtown Fitness Circuit",
      author: "ATX Morning Club",
      placeIds: ["republic-square-bars", "butler-track", "lady-bird-trail-auditorium", "barton-hills-stairs"],
      votes: 21,
      vibe: "Mixed Session",
    },
    {
      id: "hill-power-hour",
      name: "Hill Power Hour",
      author: "Hill Repeat Crew",
      placeIds: ["south-lamar-hill", "mt-bonnell-climb", "river-place-climb"],
      votes: 17,
      vibe: "Hill Session",
    },
    {
      id: "trail-and-track-combo",
      name: "Trail + Track Combo",
      author: "Austin Endurance Group",
      placeIds: ["shoal-creek-trail", "austin-high-track", "walnut-creek-trail"],
      votes: 14,
      vibe: "Endurance",
    },
  ],
};
