window.MAPBOX_CONFIG = {
  accessToken: "pk.REPLACE_WITH_YOUR_MAPBOX_ACCESS_TOKEN",
  style: "mapbox://styles/mapbox/standard",
  lightPreset: "day",
  showPointOfInterestLabels: false,
  showPlaceLabels: true,
  showRoadLabels: true,
  showTransitLabels: false,
  center: [-97.7431, 30.2672], // Austin, TX
  zoom: 12,
  pitch: 58,
  bearing: -25,
  useRoadRouting: true,
  routeProfile: "walking", // walking | cycling | driving
  // Set to true to load coffee, bar, restaurant from Mapbox Search (Austin bbox). Merged with placesCatalog.
  loadPlacesFromMapbox: false,
  searchBbox: "-97.95,30.10,-97.56,30.52", // optional; [minLon,minLat,maxLon,maxLat]
  placesCatalog: [
    {
      id: "houndstooth",
      name: "Houndstooth Coffee",
      coordinates: [-97.7425, 30.2678], // [lng, lat]
      category: "coffee",
      address: "401 Congress Ave, Austin, TX",
      website: "https://houndstoothcoffee.com",
    },
    {
      id: "merit",
      name: "Merit Coffee",
      coordinates: [-97.7499, 30.2686],
      category: "coffee",
      address: "222 West Ave, Austin, TX",
      website: "https://meritcoffee.com",
    },
    {
      id: "joes",
      name: "Jo's Coffee",
      coordinates: [-97.7479, 30.2506],
      category: "coffee",
      address: "1300 S Congress Ave, Austin, TX",
      website: "https://joscoffee.com",
    },
    {
      id: "fleet",
      name: "Fleet Coffee",
      coordinates: [-97.7259, 30.2648],
      category: "coffee",
      address: "2427 Webberville Rd #110, Austin, TX",
      website: "https://fleetcoffee.com",
    },
    {
      id: "cosmic",
      name: "Cosmic Coffee + Beer Garden",
      coordinates: [-97.7691, 30.2349],
      category: "coffee",
      address: "121 Pickle Rd, Austin, TX",
      website: "https://cosmiccoffeebeer.com",
    },
    {
      id: "civil-goat",
      name: "Civil Goat Coffee",
      coordinates: [-97.775, 30.2803],
      category: "coffee",
      address: "704 Cuernavaca Dr N, Austin, TX",
      website: "https://civilgoat.com",
    },
    {
      id: "odd-duck",
      name: "Odd Duck",
      coordinates: [-97.7494, 30.2495],
      category: "restaurant",
      address: "1201 S Lamar Blvd, Austin, TX",
      website: "https://oddduckaustin.com",
    },
    {
      id: "uchi",
      name: "Uchi",
      coordinates: [-97.7497, 30.2578],
      category: "restaurant",
      address: "801 S Lamar Blvd, Austin, TX",
      website: "https://uchiaustin.com",
    },
    {
      id: "intero",
      name: "Intero",
      coordinates: [-97.732, 30.2467],
      category: "restaurant",
      address: "2612 E Cesar Chavez St, Austin, TX",
      website: "https://interorestaurant.com",
    },
    {
      id: "launderette",
      name: "Launderette",
      coordinates: [-97.7219, 30.2607],
      category: "restaurant",
      address: "2115 Holly St, Austin, TX",
      website: "https://launderetteaustin.com",
    },
    {
      id: "canje",
      name: "Canje",
      coordinates: [-97.7147, 30.2771],
      category: "restaurant",
      address: "1914 E 6th St, Austin, TX",
      website: "https://canjeatx.com",
    },
    {
      id: "roosevelt-room",
      name: "The Roosevelt Room",
      coordinates: [-97.739, 30.2672],
      category: "bar",
      address: "307 W 5th St, Austin, TX",
      website: "https://therooseveltroomatx.com",
    },
    {
      id: "nickel-city",
      name: "Nickel City",
      coordinates: [-97.7182, 30.2619],
      category: "bar",
      address: "1133 E 11th St, Austin, TX",
      website: "https://nickelcitybar.com",
    },
    {
      id: "whislers",
      name: "Whisler's",
      coordinates: [-97.7239, 30.2644],
      category: "bar",
      address: "1816 E 6th St, Austin, TX",
      website: "https://whislersatx.com",
    },
    {
      id: "small-victory",
      name: "Small Victory",
      coordinates: [-97.7421, 30.2668],
      category: "bar",
      address: "108 E 7th St, Austin, TX",
      website: "https://smallvictory.bar",
    },
    {
      id: "deep-eddy",
      name: "Deep Eddy Cabaret",
      coordinates: [-97.7738, 30.2788],
      category: "bar",
      address: "2315 Lake Austin Blvd, Austin, TX",
      website: "https://deepeddycabaret.com",
    },
  ],
  defaultRun: ["houndstooth", "odd-duck", "roosevelt-room"],
  communityRuns: [
    {
      id: "lady-bird-trail-run",
      name: "Lady Bird Trail Run",
      author: "ATX Morning Club",
      placeIds: ["joes", "fleet", "launderette", "roosevelt-room"],
      votes: 18,
    },
    {
      id: "bar-crawl-challenge",
      name: "Bar Crawl Challenge",
      author: "Night Shift Crew",
      placeIds: ["roosevelt-room", "small-victory", "whislers", "nickel-city"],
      votes: 27,
    },
    {
      id: "jacks-birthday-pub-crawl",
      name: "Jack's Birthday Pub Crawl",
      author: "Jack",
      placeIds: ["deep-eddy", "roosevelt-room", "whislers", "nickel-city"],
      votes: 12,
    },
  ],
};
